doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'  # Adjust the path as necessary
    storage:
        table_storage:
            table_name: migration_versions
    all_or_nothing: true
    check_database_platform: true
